Download button feature
MutluMinds/fullstack-image-app pull request #70
Opened 2023-01-05 03:29 UTC by elyessAR

## Fixes Issue

Closes issue  #66 

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-05 03:48 UTC, elyessAR commented
oh well! it's not working as expected in the deploy-preview, the downloaded file name isn't what supposed to be, also the file extension should be ".jpg" in pixabay and unsplash not "jfif". 
on my machine:
![ss1](https://user-images.githubusercontent.com/49849558/210697428-e74ce92d-4ad1-403e-b252-f064fbbfd80c.png)
in preview:
![ss2](https://user-images.githubusercontent.com/49849558/210697469-ab16020c-c7e9-4bad-948f-ce87b2fee72a.png)

2023-01-05 17:43 UTC, furkanmutlu requested changes

2023-01-05 17:43 UTC, furkanmutlu commented on frontend/src/components/Gallery/Gallery.jsx
> +import { saveAs } from 'file-saver'
please follow the common style of the project. Use `"` instead of `'`

2023-01-05 17:43 UTC, furkanmutlu commented on frontend/src/components/Gallery/Gallery.jsx
> +const Gallery = ({ images, apiType }) => {
No need space here

2023-01-05 17:43 UTC, furkanmutlu commented on frontend/src/components/Gallery/Gallery.jsx
> +                  onDownload={() => handleDownload({ src, downloadable })}
you can import `saveAs` as `onDownload`. then pass it in here.
Like: `onDownload={() => onDownload(src, downloadable)}`

2023-01-05 17:45 UTC, furkanmutlu commented
> any ideas @furkanmutlu ?

Yes, its because backend app and frontend app is on different server. You need to merge backend changes first to be able to see changes on frontend deploy env. So don't worry about it.

2023-01-07 22:01 UTC, furkanmutlu approved these changes
lgtm!

2023-01-07 22:01 UTC, merged